name: Run Laravel Commands on Railway

on:
  workflow_dispatch:

jobs:
  run_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Laravel Commands
        run: |
          chmod -R 775 storage
          chmod -R 775 public/storage
          php artisan storage:link
          php artisan config:clear
          php artisan cache:clear
